--------------------------------------------------------
--  File created - Friday-January-31-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CMP_USER_PARAM_CONFIG
--------------------------------------------------------

  CREATE TABLE "CMP_USER_PARAM_CONFIG" ("RUN_DATETIME" DATE, "RUN_ID" NUMBER, "RUN_DESCRIPTION" VARCHAR2(200 CHAR), "ENVIRONMENT" VARCHAR2(3 CHAR), "DB_SCHEMA" VARCHAR2(20 CHAR), "PREFIX" VARCHAR2(3 CHAR), "TABLESPACE" VARCHAR2(2000 CHAR), "LEFT_SUFFIX" VARCHAR2(8 CHAR), "RIGHT_SUFFIX" VARCHAR2(8 CHAR), "SPOOL_OUTPUT_DIR" VARCHAR2(2000 CHAR), "COMPARE_BIN_DIR" VARCHAR2(2000 CHAR), "COMPARE_SQL_DIR" VARCHAR2(2000 CHAR), "LEFT_SUFFIX_CLEAN" VARCHAR2(8 CHAR), "RIGHT_SUFFIX_CLEAN" VARCHAR2(8 CHAR), "ORACLE_HOME" VARCHAR2(2000 CHAR), "LD_LIBRARY_PATH" VARCHAR2(2000 CHAR), "TEC_COL_1" VARCHAR2(2000 CHAR), "TEC_COL_2" VARCHAR2(2000 CHAR), "TEC_COL_3" VARCHAR2(2000 CHAR), "TEC_COL_4" VARCHAR2(2000 CHAR), "TEC_COL_5" VARCHAR2(2000 CHAR), "TEC_COL_6" VARCHAR2(2000 CHAR), "TEC_COL_7" VARCHAR2(2000 CHAR), "TEC_COL_8" VARCHAR2(2000 CHAR), "TEC_COL_9" VARCHAR2(2000 CHAR), "TEC_COL_10" VARCHAR2(2000 CHAR), "LOCKED_YN" NUMBER(1,0), "DB_SCHEMA_PWD" VARCHAR2(50), "DB_SID" VARCHAR2(100), "SRC_SCHEMA" VARCHAR2(100 CHAR), "USER_NAME" VARCHAR2(30 CHAR), "USED_BY" VARCHAR2(30 CHAR), "EXT_IND" VARCHAR2(1 CHAR))
/
--------------------------------------------------------
--  DDL for Index UNIQUE_RUN_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIQUE_RUN_ID" ON "CMP_USER_PARAM_CONFIG" ("RUN_ID")
/
--------------------------------------------------------
--  Constraints for Table CMP_USER_PARAM_CONFIG
--------------------------------------------------------

  ALTER TABLE "CMP_USER_PARAM_CONFIG" ADD CONSTRAINT "UNIQUE_RUN_ID" UNIQUE ("RUN_ID") ENABLE
/
