--------------------------------------------------------
--  File created - Friday-January-31-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CMP_USER_CONSTRAINTS_ANL
--------------------------------------------------------

  CREATE TABLE "CMP_USER_CONSTRAINTS_ANL" ("TAB" VARCHAR2(30 CHAR), "COL" VARCHAR2(30 CHAR), "POS" NUMBER(1,0), "MAXPOS" NUMBER(1,0), "UNQ_CONS" NUMBER(1,0), "UNQ_CONS_ID" VARCHAR2(20 CHAR), "TEC_UNQ_CONS" NUMBER(1,0), "TEC_UNQ_CONS_ID" VARCHAR2(20 CHAR), "FK_CONS" NUMBER(1,0), "FK_CONS_ID" VARCHAR2(20 CHAR), "FK_TAB" VARCHAR2(30 CHAR), "FK_COL" VARCHAR2(30 CHAR), "EXCLUDE_COL" NUMBER(1,0), "NON_STND_TEC_COL" NUMBER(1,0), "ANL_UNQCONS_NEXISTS_LYN" NUMBER(1,0), "ANL_UNQCONS_UNIQUE_LYN" NUMBER(1,0), "ANL_UNQCONS_NULL_LYN" NUMBER(1,0), "ANL_TECUNQ_DUBBEL_LYN" NUMBER(1,0), "ANL_TECUNQ_CONS_UNIQUE_LYN" NUMBER(1,0), "ANL_TECUNQ_CONS_INTSEC_LYN" NUMBER(1,0), "ANL_FKCONS_WITHOUT_LYN" NUMBER(1,0), "ANL_ONLYCOL_L" NUMBER(1,0), "ANL_UNQCONS_NEXISTS_RYN" NUMBER(1,0), "ANL_UNQCONS_UNIQUE_RYN" NUMBER(1,0), "ANL_UNQCONS_NULL_RYN" NUMBER(1,0), "ANL_TECUNQ_DUBBEL_RYN" NUMBER(1,0), "ANL_TECUNQ_CONS_UNIQUE_RYN" NUMBER(1,0), "ANL_TECUNQ_CONS_INTSEC_RYN" NUMBER(1,0), "ANL_FKCONS_WITHOUT_RYN" NUMBER(1,0), "ANL_ONLYCOL_R" NUMBER(1,0), "RUN_ID" VARCHAR2(200 CHAR), "ANL_DATATYPE_DIFF_LNY" NUMBER(1,0), "ANL_DATATYPE_DIFF_RNY" NUMBER(1,0), "ANL_FKCONS_WITHOUT_DATA_LYN" NUMBER(1,0), "ANL_FKCONS_WITHOUT_DATA_RYN" NUMBER(1,0), "ANL_TECUNQ_NULL_LYN" NUMBER(1,0), "ANL_TECUNQ_NULL_RYN" NUMBER(1,0))
/
